"""drop plant_subtype and note

Revision ID: 380defc4f02e
Revises: 
Create Date: 2026-04-28 14:54:30.103856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380defc4f02e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvests', 'plant_subtype')
    op.drop_column('harvests', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvests', sa.Column('note', sa.TEXT(), nullable=False))
    op.add_column('harvests', sa.Column('plant_subtype', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
