"""removed count_unit

Revision ID: 95da640e5993
Revises: 380defc4f02e
Create Date: 2026-05-17 22:56:43.497593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95da640e5993'
down_revision: Union[str, Sequence[str], None] = '380defc4f02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvests', 'count_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvests', sa.Column('count_unit', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
